# Client level configurations, common across all sites to be monitored

defaultConfig:
  api_timeout: 10      # Api timeout in seconds
  wait_time: 10           # Application Retry Wait time in seconds

stats:
  endpoint:
    hostname: "127.0.0.1"
    port: 8443
  auth:
    user: ""
    pass: ""

proxyConfig:
  enabled: false
  host: "localhost"
  port: 80
  username: ""
  password: ""

metrics:
- name: "queriesType"
  alias: "Queries Type"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "authFailures"
  alias: "Authentication Failures"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "authSuccesses"
  alias: "Authentication Successes"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "cacheFlushes"
  alias: "Cache Flushes"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "cacheOverflow"
  alias: "Cache Overflow"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "clientConnects"
  alias: "Client Connects"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "clientDisconnects"
  alias: "Client Disconnects"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "clientFails"
  alias: "Client Fails"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "clientSessions"
  alias: "Client Sessions"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "dnsFails"
  alias: "DNS Fails"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "dnsResponses"
  alias: "DNS Responses"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "dnsRequests"
  alias: "DNS Requests"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "dnsResponsesWithError"
  alias: "DNS Responses With Error"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "dnsResponsesWithNodata"
  alias: "DNS Responses With NoData"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "dnsResponsesWithNxdomain"
  alias: "DNS Responses With NxDomain"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
- name: "dnsResponsesWithRefused"
  alias: "DNS Responses With Refused"
  aggregationType: "AVERAGE"
  timeRollUpType: "AVERAGE"
  clusterRollUpType: "INDIVIDUAL"
